### ISSUE TITLE
Bad/wrong versioning

### ISSUE THREAD

**Issue by caseyhoward** [AntouanK/gulp-wrapper#3]
The versioning in this project is completely wrong:

     '0.1.0': '2014-03-18T09:52:46.250Z',
     '0.1.1': '2014-03-18T10:25:31.314Z',
     '0.1.2': '2014-03-18T10:43:59.373Z',
     '0.1.3': '2014-03-18T22:22:50.174Z',
     '0.1.31': '2014-03-18T22:50:59.999Z',
     '0.1.32': '2014-03-19T09:43:14.828Z',
     '0.1.4': '2014-06-06T16:32:43.823Z',
     '0.1.41': '2014-06-13T16:11:17.747Z',
     '0.1.42': '2014-06-13T16:26:17.329Z',
     '0.1.5': '2014-07-22T09:20:24.975Z'

When you run "npm outdated" you'll see following:

Package       Current   Wanted   Latest  Location
gulp-wrapper   0.1.42   0.1.42    0.1.5  gulp-wrapper

npm pulls down 0.1.42 since it is a higher version than 0.1.5 (42 > 5). However, version 0.1.5 was created after version 0.1.42 so npm knows it is more recent when running npm outdated but npm install resolves dependencies based on versions.

The next version of this project should be 0.1.43 or preferably 0.2.0.

**Comment by AntouanK** [comment]
@caseyhoward 
I had no idea how semver works at the time.
Right now, I would take it to 1.0.0, since 0.x.x is bad idea for anything other than experimenting.
In fact, I'll just do that, to avoid those issues.

Thanks for pointing it out.

**Comment by caseyhoward** [comment]
Awesome. Thanks.
