### ISSUE TITLE
Using filename puts a slash in the name

### ISSUE THREAD

**Issue by VincentVToscano** [AntouanK/gulp-wrapper#4]
Everytime I run the following code, I get a slash before the filename

```
return gulp
        .src('src/templates/*.handlebars')
        .pipe(hb({
            data: 'src/dataCompiled/dataCompiled.json'
        }))
        .pipe(gulp.dest('src/templatesProcessed/'))
         .pipe(wrapper({
         header: '<script type="text/x-handlebars-template" id="${filename}">\n',
         footer: '</script>\n'
         }))
```

Result:

```
 <script type="text/x-handlebars-template" id="/Projects.handlebars">
```

gulp-wrapper 1.0.0

**Comment by AntouanK** [comment]
@VincentVToscano What the plugin does is get the `file.path` and remove the `.base`. See [here](https://github.com/AntouanK/gulp-wrapper/blob/master/index.js#L34)

What OS you are using?

**Comment by VincentVToscano** [comment]
I am using OS X 10.9.5
When I console.log **_file.base**_ I get:

```
/Volumes/myhd/project1/src/templatesProcessed
```

When I console.log **_fileName**_ I get:

```
/Projects.handlebars
```

Removing **_.base**_ fileName looks like this:

```
/Volumes/myhd/project1/src/templatesProcessed/Projects.handlebars
```

**Comment by AntouanK** [comment]
Can you tell me version of `gulp` and `node` you use?

I run the tests and I print the `file.path`, `file.base` and `fileName`.
  Code:

``` javascript
console.log('---');
console.log('file.path:', file.path);
console.log('file.base:', file.base);
console.log('fileName: ', fileName);
console.log('---');
```

  Output

``` bash
---
file.path: ./test/fixture/file.js
file.base: ./test/fixture/
fileName:  file.js
---
```

I have OSX also.

**Comment by VincentVToscano** [comment]
Node:
v0.12.2

Gulp:
CLI version 3.8.8
Local version 3.8.11

Output:

```
---
file.path: /Volumes/myhd/project1/src/templatesProcessed/Projects.handlebars
file.base: /Volumes/myhd/project1/src/templatesProcessed
fileName:  /Projects.handlebars
---
```

**Comment by AntouanK** [comment]
Now that is interesting.

Can you insert the `console.log` statements in the `node_modules/gulp-wrapper/index.js` file ( let's say line 40 ) and then run `npm test` from a terminal while inside `node_modules/gulp-wrapper` directory?
Just want to see whether you get the same results there.
So that we know if it's a file specific issue or something else.

**Comment by AntouanK** [comment]
That `file` object comes from the [`vinyl`](https://github.com/wearefractal/vinyl) package.
As you can see in the README there, the `.base` should include the final slash, and the rest should be the filename.

**Comment by VincentVToscano** [comment]
npm test results:

```
> gulp-wrapper@1.0.0 test /Volumes/myhd/project1/node_modules/gulp-wrapper
> node node_modules/eslint/bin/eslint.js index.js && node_modules/.bin/mocha -R spec

module.js:338
    throw err;
          ^
Error: Cannot find module '/Volumes/myhd/project1/node_modules/eslint/bin/eslint.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

**Comment by AntouanK** [comment]
I guess you have to install the dev dependencies. Just do `npm install` in that directory to get them.

**Comment by VincentVToscano** [comment]
Results:

```
  gulp-wrapper
    wrapper()
      ✓ should pass file when it isNull()
      ✓ should emit error when file isStream()
      ✓ should add nothing without options
      ✓ should add a "<script> header"
      ✓ should add a "</script> footer"
      ✓ should add a "<script> header" and a "</script> footer"
      ✓ should add a "<script id="file.js"> header" and a "</script> footer"
      ✓ should accept functions as header and footer options
```

**Comment by AntouanK** [comment]
So when running the test, you get `file.js` as you can see. As expected.
There's something with the file or the directory you use in your example...
Is it on an external disk?
